import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { postApiResponse } from "@/api/apiUtils";
import { useEffect, useRef, useState } from "react";
import { IconButton, Stack, TextField, Typography } from "@mui/material";
import { SendRounded } from "@mui/icons-material";
import CustomizedField from "@/components/Field";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const initialHistory = [];
  const inputRef = useRef();
  const [history, setHistory] = useState(initialHistory);
  const handleClick = async () => {
    const value = inputRef.current.inputLnp?.value;
    const result = await postApiResponse({
      url: "/apis/predict",
      body: {
        email: value,
      },
    });
    const item = { ...result, mail: value }
    setHistory([item, ...history]);
  };
  return (
    <>
      <Head>
        <title>Spam classifier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.description}>
          <p>Đề tài: Phân loại thư rác</p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              Nhóm 7
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Stack width={1} spacing={2} component={"form"} ref={inputRef}>
            <CustomizedField
              placeholder="Nhập mẫu câu cần kiểm tra"
              multiline
              id="inputLnp"
              endAdornment={
                <IconButton onClick={() => handleClick()}>
                  <SendRounded></SendRounded>
                </IconButton>
              }
            ></CustomizedField>

            {history?.length > 0 && (
              <Stack spacing={2}>
                <Typography>History</Typography>
                {history?.map((item, index) => (
                  <Stack key={index} direction={'row'} spacing={2}>
                    <Typography>{index + 1}</Typography>
                    <Stack direction={"row"} justifyContent={'space-around'} width={1}>
                      <Typography sx={{width: "50%"}}>Email: {item?.mail ? item.mail : ''}</Typography>
                      <Typography>SVM: {item?.svm ? 'spam' : 'ham'}</Typography>
                      <Typography>NB: {item?.nb ? 'spam' : 'ham'}</Typography>
                      <Typography>CNN: {item?.cnn ? 'spam' : 'ham'}</Typography>
                    </Stack>
                  </Stack>
                ))}
              </Stack>
            )}
          </Stack>
        </div>
      </main>
    </>
  );
}
